### PR TITLE
Use CSS transforms instead of zoom CSS

### PR DESCRIPTION
**Pull request by ADobin**
This fixes issues with Firefox and Microsoft Edge where zoom doesn't work correctly. Based on http://caniuse.com/#search=zoom Zoom isn't even supported in FF and based on my current builds of Edge it doesn't work correctly and causes the wrong pictures to show. This fixes both of those issues and gives the same results.

image

### CODE REVIEW

**Comment by joel1st** [comment]
Nice job!

**Comment by joel1st** [comment]
Just getting a few padding issues because of how it was set up for zoom - I'll fix it up when I get home and then merge in again.

**Comment by ADobin** [comment]
Sounds good, sorry I didn't notice the padding issues.

**Comment by joel1st** [comment]
Sweet - all merged! thanks again :)

**Pull request merged**
